

services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    command: mongod --noauth
    networks:
      - app-network

  backend:
    build:
      context: ./Server
    volumes:
      - ./ssl:/ssl
      - ./Server:/app
      - /app/node_modules
      - ./Server/public/uploads:/app/Server/public/uploads
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./Client:/app
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge